name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: checkout datasketches-cpp
      uses: actions/checkout@v4
      with:
        repository: apache/datasketches-cpp
        path: datasketches-cpp
    - name: download Boost
      run: make boost
    - name: install PostgreSQL
      run: |
        sudo apt update
        sudo apt -y install postgresql-16 postgresql-client-16 postgresql-server-dev-16 libpq-dev
    - name: make
      run: make
    - name: install
      run: sudo make install
    - name: start server
      run: |
        sudo systemctl start postgresql.service
        pg_isready
    - name: create test database
      run: sudo -u postgres createdb test
    - name: copy tests
      run: cp -r test /tmp
    - name: run tests
      run: sudo -u postgres bash -c "cd; for t in /tmp/test/*.sql; do psql test -f \$t; done"
